### PR TITLE
simple change to Introduction, without making it shorter

### PR DESCRIPTION
**Pull request by danwing**

### CODE REVIEW

**Comment by boucadair** [comment]
Wanted to create a PR against Dan's one but mistakenly committed there. 

FWIW, it is easy to use the diff to track the changes: https://author-tools.ietf.org/api/iddiff?url_1=https://SpencerDawkins.github.io/net-collab-rqmts/draft-kwbdgrr-tsvwg-net-collab-rqmts.txt&url_2=https://SpencerDawkins.github.io/net-collab-rqmts/introduction_tweak/draft-kwbdgrr-tsvwg-net-collab-rqmts.txt

**Review by boucadair — APPROVED** [review]

**Review by John-Kaippallimalil — APPROVED** [review]
Looks great.

**Comment by danwing** [comment]
> Wanted to create a PR against Dan's one but mistakenly committed there.
> 
> FWIW, it is easy to use the diff to track the changes: https://author-tools.ietf.org/api/iddiff?url_1=https://SpencerDawkins.github.io/net-collab-rqmts/draft-kwbdgrr-tsvwg-net-collab-rqmts.txt&url_2=https://SpencerDawkins.github.io/net-collab-rqmts/introduction_tweak/draft-kwbdgrr-tsvwg-net-collab-rqmts.txt

Thanks for the link, that eased comparison.

I see new:

> 	7.3.  Abuse and Constraints	
> 		
> 	   It is important that not every flow be prioritized; 

Flows can be prioritized against each other?  I mean, I agree we want that in the future.  But the new text brings a new idea:  have the ISP router be where the client's various non-cooperating applications "fight it out" for which flow is prioritized.  That is a different model than what I had envisioned previously (my previous mental model is some software library on the client would "fight it out").  Doing this at the ISP router might well be a good solution, *and* it allows a subversive ISP (read: all of them) to favor one flow over another (Facebook versus Dan-Tube, my new streaming video service).

**Review by danwing — COMMENTED** [review]
Med, it appears your commit (83ff26f5c920f9fa5ec9ca9fe27643ba13862828) got lost.

Update: Nevermind, the text I was attributing to you as 'new' was text Sridharan had moved around in a separate commit. My mistake.

**Pull request merged**
