### PR TITLE
remove REQ-METADATA-ACCURACY

### PR DESCRIPTION
**Pull request by danwing**
I will wait for all co-authors to approve this change before commiting to Main.

### CODE REVIEW

**Comment by sridharangirish91** [comment]
Hey Dan, I've covered this in my PR too along with other text. Can we shelve this PR?

**Comment by danwing** [comment]
Let's have all co-authors agree to nuke this REQ, then we can close this PR and commit the change in your #87.

**Comment by boucadair** [comment]
This REQ covers the ops complexity for network-originated metadata (scone-like). Now that we focus on H2N and S2N, I'm OK to delete this text or move to an appendix. Thanks

**Comment by boucadair** [comment]
I think this can be closed now that @sridharangirish91 has merged his #87

**Pull request closed without merging**
